const TOP_LEFT = 'TOP_LEFT';
const TOP_CENTER = 'TOP_CENTER';
const TOP_RIGHT = 'TOP_RIGHT';
const MIDDLE_LEFT = 'MIDDLE_LEFT';
const MIDDLE_RIGHT = 'MIDDLE_RIGHT';
const BOTTOM_LEFT = 'BOTTOM_LEFT';
const BOTTOM_CENTER = 'BOTTOM_CENTER';
const BOTTOM_RIGHT = 'BOTTOM_RIGHT';

export const HANDLE_POSITIONS = {
  TOP_LEFT,
  TOP_CENTER,
  TOP_RIGHT,
  MIDDLE_LEFT,
  MIDDLE_RIGHT,
  BOTTOM_LEFT,
  BOTTOM_CENTER,
  BOTTOM_RIGHT,
};

export const ALL_HANDLE_POSITIONS = Object.keys(HANDLE_POSITIONS);
